message = 'Hello' + ' ' + 'World'

print(message[0:1])
print(message[0:2])
print(message[0:3])
print(message[0:4])
print(message[0:5])
print(message[0:6])
print(message[0:7])
print(message[0:8])
print(message[0:9])
print(message[0:10])
print(message[0:11])
print("Starting index is at 0||",message[:11])
print("Ending index is the last character||",message[0:])